Check that `Include` and `Exclude` paths exist
lxxxvi/ruboclean pull request #33
Opened 2024-01-17 19:39 UTC by issyl0

Hi there! Thanks for building this tool, I really like it! Feel free to take or leave this PR, but I thought it would be useful to add a feature to check that paths really exist.

This adds a `PathCleanup` class that removes any paths in the `Include` and `Exclude` lists that don't exist (relative to the `.rubocop.yml`, ignoring paths with globs).

This is useful for when you have a `.rubocop.yml` file that has been around for a while and has lots of paths that people forget to clean up when they delete the files, so doing so manually would be tedious.

2024-01-19 06:56 UTC, lxxxvi commented
Hi @issyl0 👋 

That's a cool feature, thank you very much for your contribution.
Let me have a look at it today or tomorrow. Will get back to you soon.

2024-01-20 08:02 UTC, lxxxvi requested changes
Thank's so much for your contribution, I left a few comments. 🙌 

I was thinking it may be nice to have a command line option to skip the path cleanup. Something similar exists for the comments called `--preserve-comments`. An idea could be that we have `--preserve-paths` which would not run the cleanup. Would you be interested in implementing this, probably in a follow up PR?

Thanks again!

2024-01-20 08:02 UTC, lxxxvi commented on lib/ruboclean/rubocop_configuration.rb
> +    def cleanup
Let's call this `path_cleanup`

2024-01-20 08:02 UTC, lxxxvi commented on lib/ruboclean/rubocop_configuration_path.rb
> +    PERMITTED_CLASSES = [Regexp, Symbol].freeze
Love the typo fix. Why do we need to permit `Symbol` though?

2024-01-20 08:02 UTC, lxxxvi commented on lib/ruboclean/path_cleanup.rb
> +          paths = @config_hash.dig(cop, kind.to_s) || @config_hash.dig(cop, kind.to_sym)
I may be wrong but I think that the YAML parser always returns `Symbol` for keys. So we don't need to check for `String` and `Symbol`. 🤷

2024-01-20 08:02 UTC, lxxxvi commented on lib/ruboclean/path_cleanup.rb
> +      @config_hash.each_with_object([]) do |item, result|
Could this be a `.filter_map` ?

2024-01-20 08:02 UTC, lxxxvi commented on lib/ruboclean/path_cleanup.rb
> +        result << cop if value.key?(kind.to_s) || value.key?(kind.to_sym)
Same here, I think omit testing for `String`, only use the latter. Also, `kind` seems to be a `Symbol` already, so `.to_sym` may not be necessary.

2024-01-20 08:02 UTC, lxxxvi commented on test/ruboclean/path_cleanup_test.rb
> +        }
Let's go crazy with this one. Let's add another key to `SomeCop` and then add another Cop entirely.

```ruby
{
  SomeCop: {
    Include: ["lib/**/*.rb", "test/fixtures/not_here.rb"],
    Exclude: ["config/**/*.rb", "test/fixtures/other_file_exists.rb", "some_other_non_existent_file.rb"],
    EnforcedStyle: "something"
  },
  SomeOtherCop: {
    EnforcedStyle: "something"
  }
}
```

In this way we could make sure there aren't any sideeffects. What do you think?

2024-01-20 22:18 UTC, issyl0 commented on lib/ruboclean/rubocop_configuration_path.rb
> +    PERMITTED_CLASSES = [Regexp, Symbol].freeze
When I ran an earlier iteration on one of the repos I tested against - `Homebrew/brew`'s `.rubocop.yml` (https://github.com/Homebrew/brew/pull/16483) - it failed without this change. But I think that was an earlier iteration of the parsing code, and I just tested again and it seems to work without it now. So I'll back this out.

2024-01-20 22:29 UTC, issyl0 commented on lib/ruboclean/path_cleanup.rb
> +      @config_hash.each_with_object([]) do |item, result|
It can be! That's cool.

2024-01-20 22:31 UTC, issyl0 commented on lib/ruboclean/path_cleanup.rb
> +          paths = @config_hash.dig(cop, kind.to_s) || @config_hash.dig(cop, kind.to_sym)
You are not wrong! 😄

2024-01-20 22:33 UTC, issyl0 commented
Thanks for the review @lxxxvi - I've made the requested changes. I'm absolutely fine to add a `--preserve-paths` - now or later?

2024-01-21 15:25 UTC, merged

2024-01-21 15:26 UTC, lxxxvi commented
@issyl0 Thanks a lot for your contribution. 🤚
It would be cool to see the `--preserve-paths` feature in a follow up!